#!/bin/csh
# Request a specified file.

# Some basic configuration
set show_replies = 1
set server      = "127.0.0.1"

if ($#argv != 3) then
  echo "Usage : $0 uri start_range end_range"
  echo "         E.g.,  docs/10B.txt 0 1"
  exit 1
endif

echo "Trying to get file = $1"
set uri         = "--uri $1"
set conns       = "--num-conns 1"
set rate        = ""
set range       = "$2-$3"

echo "range = $range"

set httperf     = "httperf"
set httpversion = "--http-version 1.1"
set timeout     = "--timeout 5"
set port        = "--port 6800"
# set extraopts   = "--verbose --hog"
set extraopts   = "--verbose --print-request"

if ($show_replies) then
  set print = "--print-reply"
else
  set print = ""
endif

$httperf $extraopts --server $server $port $httpversion $uri \
         $conns $timeout $print $rate --add-header "Range : bytes=$range"

exit $status
